// vuejs-files/template-rtl/src/views/page/error/error500.vue
<template>

	<div class="error404 error-page" style="height: 100vh !important;">

		<!-- Main Wrapper -->
        <div class="main-wrapper text-center" style="visibility: visible;">
			
			<div class="error-box">
				<h1>500</h1>
				<h3><i class="fa fa-warning"></i> Oops! Something went wrong</h3>
				<p>The page you requested was not found.</p>
				<router-link to="/index" class="btn btn-custom btn-gradient-primary btn-rounded">Back to Home</router-link>
			</div>
		
        </div>
		<!-- /Main Wrapper -->

	</div>

</template>

<script>
	export default {
		mounted() {
	},
    data() {
        return {
        }
    }
    }
</script>

// reactjs-files/template/src/components/error/error-500/index.jsx
import React, { useEffect, useState } from "react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";

const Error500 =()=> {
//   useEffect(() => {
//     document.body.classList.add('error-page');
//     return () => document.body.classList.remove("error-page");
// }, [])
    return (     
      <>
        <Helmet>
              <title>Error 500 - CRMS Admin Template</title>
              <meta name="description" content="Error"/>					
        </Helmet>
        <div className="error-box">
          <h1>500</h1>
          <h3><i className="fa fa-warning"></i> Oops! Something went wrong</h3>
          <p>The page you requested was not found.</p>
          {/* <Link onClick={() => localStorage.setItem("firstload", "true")} to="/" className="btn btn-custom btn-gradient-primary btn-rounded">Back to Home</Link > */}
          <a href="/index" className="btn btn-custom btn-gradient-primary btn-rounded">Back to Home</a>
        </div>		
      </>
    );
  }

export default Error500;
