// reactjs-files/template/src/components/error/error-404/index.jsx
import React, { useEffect, useState } from "react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";

const Error404 =()=> {
  // useEffect(() => {
  //   document.body.classList.add('error-page');
  //   return () => document.body.classList.remove("error-page");
  // }, [])
    return (
        <>
          <Helmet>
                <title>Error 404 - CRMS Admin Template</title>
                <meta name="description" content="Login page"/>					
          </Helmet>
          <div className="error-box">
            <h1>404</h1>
            <h3> <i className="fa fa-warning"></i> Oops! Page not found! </h3>
            <p>The page you requested was not found.</p>
            {/* <Link onClick={() => localStorage.setItem("firstload", "true")} to="/index" className="btn btn-custom btn-gradient-primary btn-rounded">Back to Home</Link > */}
            <a href="/index" className="btn btn-custom btn-gradient-primary btn-rounded">Back to Home</a>
          </div>
        </>
    );
  }
export default Error404;

// vuejs-files/template-rtl/src/views/page/error/error404.vue
<template>

	<div class="error404 error-page" style="height: 100vh !important;">

		<!-- Main Wrapper -->
        <div class="main-wrapper text-center" style="visibility: visible;">
			
			<div class="error-box">
				<h1>404</h1>
				<h3><i class="fa fa-warning"></i> Oops! Page not found!</h3>
				<p>The page you requested was not found.</p>
				<router-link to="/index" class="btn btn-custom btn-gradient-primary btn-rounded">Back to Home</router-link>
			</div>
		
        </div>
		<!-- /Main Wrapper -->

	</div>

</template>

<script>
	export default {
		mounted() {
	},
    data() {
        return {
        }
    }
    }
</script>
