// angular-files/template/src/app/all-modules/blog/categories/categories.component.ts
import { Component, OnInit} from '@angular/core';
import { routes } from 'src/app/shared/core.index';
import { DataService } from "src/app/shared/data/data.service";
import { MatTableDataSource } from "@angular/material/table";
import { pageSelection, apiResultFormat, categories } from 'src/app/shared/models/models';
import { Sort } from '@angular/material/sort';


@Component({
  selector: 'app-categories',
  templateUrl: './categories.component.html',
  styleUrls: ['./categories.component.scss']
})
export class CategoriesComponent implements OnInit {
public routes = routes;
public categories: Array<categories> = [];
dataSource!: MatTableDataSource<categories>;

public showFilter = false;
public searchDataValue = '';
// pagination variables
public lastIndex = 0;
public pageSize = 10;
public totalData = 0;
public skip = 0;
public limit: number = this.pageSize;
public pageIndex = 0;
public serialNumberArray: Array<number> = [];
public currentPage = 1;
public pageNumberArray: Array<number> = [];
public pageSelection: Array<pageSelection> = [];
public totalPages = 0;
//** / pagination variables


constructor(private data: DataService ) { }

ngOnInit() {
  this.getTableData();
}
private getTableData(): void {
  this.categories = [];
  this.serialNumberArray = [];

  this.data.getCategories().subscribe((data: apiResultFormat) => {
    this.totalData = data.totalData;
    data.data.map((res: categories, index: number) => {
      const serialNumber = index + 1;
      if (index >= this.skip && serialNumber <= this.limit) {
        res.id = serialNumber;
        this.categories.push(res);
        this.serialNumberArray.push(serialNumber);
      }
    });
    this.dataSource = new MatTableDataSource<categories>(this.categories);
    this.calculateTotalPages(this.totalData, this.pageSize);
  });
}

public searchData(value: string): void {
  this.dataSource.filter = value.trim().toLowerCase();
  this.categories = this.dataSource.filteredData;
}

public sortData(sort: Sort) {
  const data = this.categories.slice();
  /* eslint-disable @typescript-eslint/no-explicit-any */
  if (!sort.active || sort.direction === '') {
    this.categories = data;
  } else {
    this.categories = data.sort((a, b) => {
      const aValue = (a as any)[sort.active];
      const bValue = (b as any)[sort.active];
      return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
    });
  }
}

public getMoreData(event: string): void {
  if (event == 'next') {
    this.currentPage++;
    this.pageIndex = this.currentPage - 1;
    this.limit += this.pageSize;
    this.skip = this.pageSize * this.pageIndex;
    this.getTableData();
  } else if (event == 'previous') {
    this.currentPage--;
    this.pageIndex = this.currentPage - 1;
    this.limit -= this.pageSize;
    this.skip = this.pageSize * this.pageIndex;
    this.getTableData();
  }
}

public moveToPage(pageNumber: number): void {
  this.currentPage = pageNumber;
  this.skip = this.pageSelection[pageNumber - 1].skip;
  this.limit = this.pageSelection[pageNumber - 1].limit;
  if (pageNumber > this.currentPage) {
    this.pageIndex = pageNumber - 1;
  } else if (pageNumber < this.currentPage) {
    this.pageIndex = pageNumber + 1;
  }
  this.getTableData();
}

public PageSize(): void {
  this.pageSelection = [];
  this.limit = this.pageSize;
  this.skip = 0;
  this.currentPage = 1;
  this.getTableData();
}

private calculateTotalPages(totalData: number, pageSize: number): void {
  this.pageNumberArray = [];
  this.totalPages = totalData / pageSize;
  if (this.totalPages % 1 != 0) {
    this.totalPages = Math.trunc(this.totalPages + 1);
  }
  for (let i = 1; i <= this.totalPages; i++) {
    const limit = pageSize * i;
    const skip = limit - pageSize;
    this.pageNumberArray.push(i);
    this.pageSelection.push({ skip: skip, limit: limit });
  }
}
}

<!-- Page Wrapper -->
<div class="page-wrapper">
    <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col">
                    <h3 class="page-title">Categories</h3>
                </div>
                <div class="col-auto text-end">
                    <a href="javascript:void(0);" class="btn btn-primary btn-blog mb-3" data-bs-toggle="modal"
                        data-bs-target="#blog-categories"><i class="feather icon-plus-circle me-1"></i> Add New</a>
                </div>
            </div>
        </div>
        <!-- /Page Header -->

        <div class="row">
            <div class="col-md-12">
                <div class="card categories-table">
                    <div class="card-body">
                        <div class="table-responsive">
                            <div class="table_header">
                                <div class="row">
                                    <div class="col-sm-12 col-md-6">
                                        <div class="dataTables_length">
                                            <label>
                                                Show
                                                <select [(ngModel)]="pageSize" (ngModelChange)="PageSize()"
                                                    class="form-control form-control-sm">
                                                    <option value="10">10</option>
                                                    <option value="25">25</option>
                                                    <option value="50">50</option>
                                                    <option value="100">100</option>
                                                </select>
                                                entries
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 col-md-6">
                                        <div class="dataTables_filter">
                                            <label>
                                                Search:
                                                <input [(ngModel)]="searchDataValue" type="search"
                                                    (ngModelChange)="searchData(searchDataValue)"
                                                    class="form-control form-control-sm" />
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <table matSort (matSortChange)="sortData($event)"
                                class="table custom-table mb-0 datatables table-nowrap">
                                <thead>
                                    <tr>
                                        <th mat-sort-header="id">#</th>
                                        <th mat-sort-header="categoryName">Category Name</th>
                                        <th mat-sort-header="date">Date</th>
                                        <th mat-sort-header="addedBy">Added By</th>
                                        <th>Status</th>
                                        <th class="text-end">Action</th>
                                    </tr>
                                </thead>
                                <tbody *ngFor="let list of categories; let i = index">
                                    <tr>
                                        <td>{{list.id}}</td>
                                        <td>{{list.categoryName}}</td>
                                        <td>{{list.date}}</td>
                                        <td>{{list.addedBy}}</td>
                                        <td>
                                            <div class="status-toggle">
                                                <input id="{{'list.id' + i}}" class="check" type="checkbox"
                                                    [(ngModel)]="list.isStatus">
                                                <label for="{{'list.id' + i}}"
                                                    class="checktoggle checkbox-bg">checkbox</label>
                                            </div>
                                        </td>
                                        <td class="text-end">
                                            <a href="javascript:void(0);"
                                                class="table-action-btn btn btn-sm bg-success-light me-1"
                                                data-bs-toggle="modal" data-bs-target="#edit-blog-categories">
                                                <i class="feather icon-edit me-1"></i> {{list.action1}}
                                            </a>
                                            <a href="javascript:void(0);"
                                                class="table-action-btn btn btn-sm bg-danger-light"
                                                data-bs-toggle="modal" data-bs-target="#deleteModal">
                                                <i class="feather icon-trash-2 me-1"></i> {{list.action2}}
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- modal -->
    <div class="modal custom-modal fade bank-details" id="blog-categories" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="form-header text-start mb-0">
                        <h4 class="mb-0 text-dark fw-bold">Add Category</h4>
                    </div>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="bank-inner-details">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Category Name<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Slug<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                    <small class="form-text text-muted">
                                        (If you leave it empty, it will be generated
                                        automatically.)</small>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Description (Meta Tag)<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Keywords (Meta Tag)<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Order<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Status</label>
                                <div class="status-toggle">
                                    <input id="rating_5" class="check" type="checkbox" checked />
                                    <label for="rating_5" class="checktoggle checkbox-bg">checkbox</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer blog-categories-btn">
                    <div class="bank-details-btn">
                        <a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary me-2">Add
                            Category</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- modal -->
    <div class="modal custom-modal fade bank-details" id="edit-blog-categories" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="form-header text-start mb-0">
                        <h4 class="mb-0 text-dark fw-bold">Edit Category</h4>
                    </div>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="bank-inner-details">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Category Name<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" value="Productivity" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Slug<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" value="Productivity" />
                                    <small class="form-text text-muted">
                                        (If you leave it empty, it will be generated
                                        automatically.)</small>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Description (Meta Tag)<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Keywords (Meta Tag)<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>Order<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Status</label>
                                <div class="status-toggle">
                                    <input id="rating_6" class="check" type="checkbox" checked />
                                    <label for="rating_6" class="checktoggle checkbox-bg">checkbox</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer blog-categories-btn">
                    <div class="bank-details-btn">
                        <a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary me-2">Add
                            Category</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade contentmodal" id="deleteModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content doctor-profile">
                <div class="modal-header pb-0 border-bottom-0 justify-content-end">
                    <button type="button" class="close-btn" data-bs-dismiss="modal" aria-label="Close">
                        <i class="feather icon-x-circle"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="delete-wrap text-center">
                        <div class="del-icon"><i class="feather icon-x-circle"></i></div>
                        <h2>Sure you want to delete</h2>
                        <div class="submit-section">
                            <a href="blog-categories.html" class="btn btn-success me-2">Yes</a>
                            <a href="javascript:void(0);" class="btn btn-danger" data-bs-dismiss="modal">No</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Modal -->
</div>
<!-- /Page Wrapper -->

// reactjs-files/template/src/components/blogs/categories/index.jsx
import React from 'react';
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import { Table } from "antd";
import { itemRender, onShowSizeChange } from "../../paginationfunction"
import { iOutlinePlusCircle } from "react-icons/ai";
import "../../antdstyle.css"
import { FiEdit, FiPlusCircle, FiTrash2, FiXCircle } from 'react-icons/fi';
const Categories = () => {
  const data = [
    {
      id: 1,
      num: 1,
      Name: "Productivity",
      Date: "10/04/22",
      Added: "Admin",
      Status: "checkbox"
    },
    {
      id: 2,
      num: 2,
      Name: "Sales",
      Date: "10/04/22",
      Added: "Admin",
      Status: "checkbox"
    },
    {
      id: 3,
      num: 3,
      Name: "Marketing",
      Date: "10/04/22",
      Added: "Admin",
      Status: "checkbox"
    },
    {
      id: 4,
      num: 4,
      Name: "Management",
      Date: "10/04/22",
      Added: "Wegman",
      Status: "checkbox"
    }
  ]
  const columns = [
    {
      title: "#",
      dataIndex: "num",
      render: (text, record) => (
        <>{text}</>
      ),
      sorter: (a, b) => a.num.length - b.num.length,
    },
    {
      title: "Category Name",
      dataIndex: "Name",
      render: (text, record) => (
        <>{text}</>
      ),
      sorter: (a, b) => a.Name.length - b.Name.length,
    },
    {
      title: "Date",
      dataIndex: "Date",
      render: (text, record) => (
        <>{text}</>
      ),
      sorter: (a, b) => a.Date.length - b.Date.length,
    },
    {
      title: "Added By",
      dataIndex: "Added",
      render: (text, record) => (
        <>{text}</>
      ),
      sorter: (a, b) => a.Added.length - b.Added.length,
    },
    {
      title: "Status",
      dataIndex: "Status",
      render: (text, record) => {
        return (
         <div className="status-toggle">
           <input
             id={`rating${record?.id}`}
             className="check"
             type="checkbox"
           />
           <label
             htmlFor={`rating${record?.id}`}
             className="checktoggle checkbox-bg"
           >
             checkbox
           </label>
         </div>
       )},
      sorter: (a, b) => a.Status.length - b.Status.length,
    },
    {
      title: "Action",
      className: "text-end",
      dataIndex: "",
      render: (text, record) => (
        <div className="text-end">
          <a
            href="#"
            className="me-1 btn btn-sm bg-success-light"
            data-bs-toggle="modal"
            data-bs-target="#edit-blog-categories"
          >
            <FiEdit className="feather-edit-3 me-1" /> Edit
          </a>
          <a
            href="#"
            className="me-1 btn btn-sm bg-danger-light"
            data-bs-toggle="modal"
            data-bs-target="#deleteModal"
          >
            <FiTrash2 className="feather-trash-2 me-1" /> Delete
          </a>
        </div>
      ),
      sorter: (a, b) => a.star.length - b.star.length,
    }
  ];
  return (
    <>
      {/* Page Wrapper */}
      <div className="page-wrapper">
        <Helmet>
          <title>Dashboard - CRMS admin Template</title>
          <meta name="description" content="Reactify Blank Page" />
        </Helmet>
        <div className="content container-fluid">
          {/* Page Header */}
          <div className="page-header">
            <div className="row">
              <div className="col">
                <h3 className="page-title">Categories</h3>
              </div>
              <div className="col-auto text-end">
                <a
                  href="#"
                  className="btn btn-primary btn-blog mb-3"
                  data-bs-toggle="modal"
                  data-bs-target="#blog-categories"
                >
                  <FiPlusCircle /> Add New
                </a>
              </div>
            </div>
          </div>
          {/* /Page Header */}
          <div className="row">
            <div className="col-md-12">
              <div className="card categories-table">
                <div className="card-body">
                  <div className="table-responsive">
                    <Table
                      className="table"
                      style={{ overflowX: "auto" }}
                      pagination={{
                        total: data.length,
                        showTotal: (total, range) => `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                        showSizeChanger: true, onShowSizeChange: onShowSizeChange, itemRender: itemRender
                      }}
                      columns={columns}
                      dataSource={data}
                      rowKey={(record) => record.id}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* modal */}
        <div
          className="modal custom-modal fade bank-details"
          id="blog-categories"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header">
                <div className="form-header text-start mb-0">
                  <h4 className="mb-0 text-dark fw-bold">Add Category</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div className="modal-body">
                <div className="bank-inner-details">
                  <div className="row">
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Category Name<span className="text-danger">*</span>
                        </label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Slug<span className="text-danger">*</span>
                        </label>
                        <input type="text" className="form-control" />
                        <small className="form-text text-muted">
                          {" "}
                          (If you leave it empty, it will be generated
                          automatically.)
                        </small>
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Description (Meta Tag)
                          <span className="text-danger">*</span>
                        </label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Keywords (Meta Tag)<span className="text-danger">*</span>
                        </label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Order<span className="text-danger">*</span>
                        </label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                    <div className="form-group">
                      <label>Status</label>
                      <div className="status-toggle">
                        <input
                          id="rating_5"
                          className="check"
                          type="checkbox"
                          defaultChecked=""
                        />
                        <label
                          htmlFor="rating_5"
                          className="checktoggle checkbox-bg "
                        >
                          checkbox
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer blog-categories-btn">
                <div className="bank-details-btn ">
                  <a
                    href="#"
                    data-bs-dismiss="modal"
                    className="btn btn-primary me-2"
                  >
                    Add Category
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* modal */}
        <div
          className="modal custom-modal fade bank-details"
          id="edit-blog-categories"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header">
                <div className="form-header text-start mb-0">
                  <h4 className="mb-0 text-dark fw-bold">Edit Category</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div className="modal-body">
                <div className="bank-inner-details">
                  <div className="row">
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Category Name<span className="text-danger">*</span>
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="Productivity"
                        />
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Slug<span className="text-danger">*</span>
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="Productivity"
                        />
                        <small className="form-text text-muted">
                          {" "}
                          (If you leave it empty, it will be generated
                          automatically.)
                        </small>
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Description (Meta Tag)
                          <span className="text-danger">*</span>
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="category Productivity"
                        />
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Keywords (Meta Tag)<span className="text-danger">*</span>
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="category Productivity"
                        />
                      </div>
                    </div>
                    <div className="col-lg-12 col-md-12">
                      <div className="form-group">
                        <label>
                          Order<span className="text-danger">*</span>
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue={3}
                        />
                      </div>
                    </div>
                    <div className="form-group">
                      <label>Status</label>
                      <div className="status-toggle">
                        <input
                          id="rating_6"
                          className="check"
                          type="checkbox"
                          defaultChecked=""
                        />
                        <label
                          htmlFor="rating_6"
                          className="checktoggle checkbox-bg "
                        >
                          checkbox
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer blog-categories-btn">
                <div className="bank-details-btn ">
                  <a
                    href="#"
                    data-bs-dismiss="modal"
                    className="btn btn-primary me-2"
                  >
                    Add Category
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Modal */}
        <div
          className="modal fade contentmodal"
          id="deleteModal"
          tabIndex={-1}
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content doctor-profile">
              <div className="modal-header pb-0 border-bottom-0  justify-content-end">
                <button
                  type="button"
                  className="close-btn"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                    <i><FiXCircle className="feather-x-circle" /></i>
                </button>
              </div>
              <div className="modal-body">
                <div className="delete-wrap text-center">
                  <div className="del-icon">
                  <i><FiXCircle className="feather-x-circle" /></i>
                  </div>
                  <h2>Sure you want to delete</h2>
                  <div className="submit-section">
                    <Link to="/categories" className="btn btn-success me-2">
                      Yes
                    </Link>
                    <a href="#" className="btn btn-danger" data-bs-dismiss="modal">
                      No
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /Modal */}
      </div>
      {/* /Page Wrapper */}
      {/* /Main Wrapper */}
      {/* Modal */}
      <div className="modal fade confirmModal" tabIndex={-1} aria-hidden="true">
        <div className="modal-dialog modal-dialog-centered">
          <div className="modal-content p-3">
            <div className="modal-header border-bottom-0">
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              />
            </div>
            <div className="modal-body">
              <div className="text-center">
                <h5 className="mb-3">Confirm Save Changes</h5>
                <button
                  type="button"
                  className="btn btn-dark w-md"
                  data-bs-dismiss="modal"
                >
                  Close
                </button>
                <button
                  type="button"
                  className="btn btn-primary w-md"
                  data-bs-dismiss="modal"
                >
                  Save changes
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>

  )
};
export default Categories;
